### ISSUE TITLE
graylogweb doesn't "restart"

### ISSUE THREAD

**Issue by kkendzia** [micahhausler/graylog-compose#5]
After stopping all services and starting them again graylogweb exits because of already existing RUNNING_PID

**Comment by petermikitsh** [comment]
@micahhausler Any idea how to fix this? I'm experiencing it as well, thanks

```
graylogweb_1     | Play server process ID is 5
graylogweb_1     | This application is already running (Or delete /opt/graylog/RUNNING_PID file).
logspout_1       | 2016/08/29 00:23:25 Graylog: write udp 172.17.0.2:12201: connection refused
graylogcompose_graylogweb_1 exited with code 255
```

**Comment by micahhausler** [comment]
Honestly, it's been a year since I've touched Graylog. I would try adding [`-np`](http://docs.graylog.org/en/2.0/pages/installation/manual_setup.html#command-line-cli-parameters) to the [Dockerfile for graylog](https://github.com/micahhausler/graylog-compose/blob/master/graylog/Dockerfile#L57).
